name : Deploy Project
on : 
  push:
  workflow_dispatch:

jobs : 
  test :
    runs-on : ubuntu-latest
    steps :

      - name : Get code from repository
        uses : actions/checkout@v7
        
      - name : Install NodeJS
        uses : actions/setup-node@v6
        with :
          node-version : 18

      - name : Cache Dependencies
        uses : actions/cache@v3
        with :
          path : ~/.npm
          key : deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name : Install dependencies
        run : npm install

      - name : Run tests
        run : npm test  

  build :
    runs-on : ubuntu-latest
    needs : test
    outputs :
      script-file-name : ${{ steps.publish-js-file-name.outputs.script-file }}
    steps :

      - name : Get code from repository
        uses : actions/checkout@v7
        
      - name : Install NodeJS
        uses : actions/setup-node@v6
        with :
          node-version : 18

      - name : Cache Dependencies
        uses : actions/cache@v3
        with :
          path : ~/.npm
          key : deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name : Install dependencies
        run : npm install

      - name : Build Project
        run : npm run build

      - name : Upload artifacts
        uses : actions/upload-artifact@v7
        with :
          name : dist-files
          path : |                  
            dist
            package.json

      - name : Publish JS file name 
        id : publish-js-file-name
        run : find dist/assets/*.js -type f -execdir echo 'script-file : {}' >> $GITHUB_OUTPUT ';'

  deploy :
    runs-on : ubuntu-latest
    needs : build
    steps :

      - name : Download artifacts
        uses : actions/download-artifact@v8
        with :
          name : dist-files
          path : ./downloaded-artifacts  

      - name : List downloaded artifacts
        run : ls -R ./downloaded-artifacts

      - name : Output script file name
        run : echo "Script file name - ${{ needs.build.outputs.script-file-name }}"

      - name : Deploy Project
        run : echo "Deploying project..."