name : Deploy Project
on : 
  push:
  workflow_dispatch:

jobs : 
  test :
    runs-on : ubuntu-latest
    steps :

      - name : Get code from repository
        uses : actions/checkout@v7
        
      - name : Install NodeJS
        uses : actions/setup-node@v6
        with :
          node-version : 18
      
      - name : Install dependencies
        run : npm install

      - name : Run tests
        run : npm test  

  deploy :
    runs-on : ubuntu-latest
    needs : test
    steps :

      - name : Get code from repository
        uses : actions/checkout@v7
        
      - name : Install NodeJS
        uses : actions/setup-node@v6
        with :
          node-version : 18
      
      - name : Install dependencies
        run : npm install

      - name : Build Project
        run : npm run build

      - name : Upload artifacts
        uses : actions/upload-artifact@v7
        with :
          name : dist-files
          path : |
            dist
            package.json

      - name : Deploy Project
        run : echo "Deploying project..."