name : Output Information
on : workflow_dispatch
jobs :
  output :
    runs-on : ubuntu-latest
    steps :
      - name : Output current date and time
        run : echo "Current date and time: $(date)"
      
      - name : Output system information
        run : echo "System information: ${{runner.os}}"
      
      - name : Output Github variables
        run : echo "Github variables: ${{ toJSON(github) }}"