name : Test Project
on : push

jobs : 
  test :
    runs-on : ubuntu-latest
    steps :

      - name : Get code from repository
        uses : actions/checkout@v7
        
      - name : Install NodeJS
        uses : actions/setup-node@v6
        with :
          node-version : 18
      
      - name : Install dependencies
        run : npm install

      - name : Run tests
        run : npm test  